version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=biblioteca
    ports:
      - 3307:3306
    volumes:
      - mysql-data-biblioteca:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

  app: 
    build: .
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 5000:5000

volumes:
  mysql-data-biblioteca: