version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "80:5000"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: biblioteca
    depends_on:
      - mysqldb
    networks:
      - biblioteca-network

  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=biblioteca
    ports:
      - 3310:3306
    volumes:
      - mysql-data-biblioteca:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

  app: 
    build: .
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 5000:5000

volumes:
  mysql-data-biblioteca:

networks:
  biblioteca-network:
    driver: bridge
